sudo: required
services:
  - docker

before_install:
  - docker build -t prakharderoliya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true prakharderoliya/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "dockerized"
  env: "Dockerized-env"
  bucket_name: aws:elasticloadbalancing:eu-central-1:984065706511
  access_key_id: $Access_Key
  secret_access_key: $Access_Secrets
  on:
    branch: main
